export default {
  version: 8,
  name: "OSM Liberty",
  metadata: {
    "maputnik:license":
      "https://github.com/maputnik/osm-liberty/blob/gh-pages/LICENSE.md",
    "maputnik:renderer": "mbgljs",
    "openmaptiles:version": "3.x",
  },
  sources: {
    igensys: {
      type: "vector",
      tiles: ["https://alpha.tiles.unl.global/v2alpha/vector/767/{z}/{x}/{y}"],
    },
  },
  sprite: "https://maputnik.github.io/osm-liberty/sprites/osm-liberty",
  glyphs:
    "https://api.maptiler.com/fonts/{fontstack}/{range}.pbf?key=xCp8xgPeanjDKCXNoO4B",
  layers: [
    {
      id: "background",
      type: "background",
      paint: { "background-color": "rgb(239,239,239)" },
    },
    {
      id: "igensys.admin_boundary5",
      type: "fill",
      source: "igensys",
      "source-layer": "admin_boundary_5",
      filter: ["all"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(239,239,239)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.admin_boundary4",
      type: "fill",
      source: "igensys",
      "source-layer": "admin_boundary_4",

      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(239,239,239)", "fill-opacity": 0.6 },
    },
    {
      id: "igensys.admin_boundary3",
      type: "fill",
      source: "igensys",
      "source-layer": "admin_boundary_3",

      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(239,239,239)", "fill-opacity": 0.9 },
    },
    {
      id: "igensys.admin_boundary2",
      type: "fill",
      source: "igensys",
      "source-layer": "admin_boundary_2",

      filter: ["all"],
      layout: { visibility: "visible" },
      paint: {
        "fill-translate-anchor": "viewport",
        "fill-opacity": 0.9,
        "fill-color": "rgba(229, 229, 229, 1)",
      },
    },
    {
      id: "igensys.landuse-Industrial_Air",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_industrial",

      filter: [
        "any",
        ["==", "name", "Chhatrapati Shivaji International Airport"],
        ["==", "name", "Juhu Domestic Airport"],
      ],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgba(198, 182, 182, 1)", "fill-opacity": 0.6 },
    },
    {
      id: "igensys.landuse-Industrial",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_industrial",

      layout: { visibility: "visible" },
      paint: { "fill-color": "rgba(168, 155, 155, 1)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.landuse_urban",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_urban",
      filter: ["all"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgba(139, 223, 155, 1)", "fill-opacity": 0.6 },
    },
    {
      id: "igensys.landuse_Others",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_Others",

      filter: ["all", ["==", "type", ""]],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgba(156, 239, 239, 1)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.landuse-green",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_green",
      filter: ["all"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgba(139, 223, 155, 1)", "fill-opacity": 0.8 },
    },
    {
      id: "igensys.landuse_hydro",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_hydro",

      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(156,192,249)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.water_small",
      type: "fill",
      source: "igensys",
      "source-layer": "water_medium",

      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(156,192,249)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.water_medium",
      type: "fill",
      source: "igensys",
      "source-layer": "water_medium",
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(156,192,249)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.water_large",
      type: "fill",
      source: "igensys",
      "source-layer": "water_large",

      filter: ["all", ["==", "name", ""]],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(156,192,249)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.rail_mini_rail",
      type: "line",
      source: "igensys",
      "source-layer": "mini_rail",

      layout: { visibility: "visible" },
      paint: {
        "line-opacity": 1,
        "line-color": "rgba(170, 157, 157, 1)",
        "line-width": 1.2,
        "line-blur": 1.3,
      },
    },
    {
      id: "igensys.rail_metro_rail",
      type: "line",
      source: "igensys",
      "source-layer": "metro_rail",

      layout: { visibility: "visible" },
      paint: {
        "line-opacity": 1,
        "line-color": "rgba(170, 157, 157, 1)",
        "line-width": 1.2,
        "line-blur": 1.2,
      },
    },
    {
      id: "igensys.rail_mono_rail",
      type: "line",
      source: "igensys",
      "source-layer": "mono_rail",

      layout: { visibility: "visible" },
      paint: {
        "line-opacity": 1,
        "line-color": "rgba(170, 157, 157, 1)",
        "line-width": 1.5,
        "line-blur": 1.5,
      },
    },
    {
      id: "igensys.rail_railroad",
      type: "line",
      source: "igensys",
      "source-layer": "railroad",

      layout: {
        visibility: "visible",
        "line-miter-limit": 2,
        "line-round-limit": 1.06,
      },
      paint: {
        "line-color": "rgba(62, 59, 59, 1)",
        "line-opacity": 1,
        "line-width": 2,
        "line-blur": 1.9,
      },
    },
    {
      id: "igensys.road_minor",
      type: "line",
      source: "igensys",
      "source-layer": "road_minor",

      filter: ["any", ["==", "name", ""]],
      layout: { visibility: "visible" },
      paint: {
        "line-color": "rgba(255, 255, 255, 1)",
        "line-width": 1.6,
        "line-opacity": 0.8,
      },
    },
    {
      id: "igensys.road_private",
      type: "line",
      source: "igensys",
      "source-layer": "road_private",

      layout: { visibility: "visible" },
      paint: {
        "line-color": "rgba(255, 255, 255, 1)",
        "line-width": 1.6,
        "line-opacity": 0.8,
      },
    },
    {
      id: "igensys.road_major_Urban",
      type: "line",
      source: "igensys",
      "source-layer": "road_major_urban",

      filter: ["all"],
      layout: { visibility: "visible" },
      paint: {
        "line-opacity": 1,
        "line-gap-width": 1.5,
        "line-width": 1.5,
        "line-blur": 1,
        "line-color": "rgba(255, 251, 251, 1)",
      },
    },
    {
      id: "igensys.road_major_district",
      type: "line",
      source: "igensys",
      "source-layer": "road_major_district",

      filter: ["any", ["has", "direction_"]],
      layout: { visibility: "visible" },
      paint: {
        "line-color": "rgba(255, 251, 251, 1)",
        "line-gap-width": 1,
        "line-offset": 0,
        "line-width": 1,
        "line-opacity": 1,
      },
    },
    {
      id: "igensys.road_state_highways",
      type: "line",
      source: "igensys",
      "source-layer": "road_state_highways",

      layout: { visibility: "visible" },
      paint: {
        "line-color": "rgba(255, 222, 65, 1)",
        "line-gap-width": 1,
        "line-opacity": 1,
        "line-width": 1,
      },
    },
    {
      id: "igensys.road_national_highways",
      type: "line",
      source: "igensys",
      "source-layer": "road_national_highways",

      layout: { visibility: "visible" },
      paint: {
        "line-color": "rgba(247, 232, 106, 1)",
        "line-gap-width": 1,
        "line-width": 1.5,
        "line-opacity": 1,
      },
    },
    {
      id: "igensys.buildings",
      type: "fill",
      source: "igensys",
      "source-layer": "buildings",

      filter: ["all"],
      layout: { visibility: "none" },
      paint: {
        "fill-color": "rgba(160, 153, 153, 1)",
        "fill-opacity": 0.9,
        "fill-outline-color": "rgba(80, 80, 75, 1)",
      },
    },
    {
      id: "igensys.rail_railway_station",
      type: "symbol",
      source: "igensys",
      "source-layer": "railway_station",

      filter: ["all"],
      layout: {
        "text-field": "{station_name}",
        visibility: "visible",
        "text-size": 8.5,
        "icon-allow-overlap": false,
        "icon-image": "ranger_station_11",
        "icon-size": 0.6,
        "icon-text-fit": "none",
        "text-max-width": 1,
      },
    },
    {
      id: "Building_3D",
      type: "fill-extrusion",
      source: "igensys",
      "source-layer": "buildings",

      filter: ["all"],
      layout: { visibility: "visible" },
      paint: {
        "fill-extrusion-color": "rgba(160, 153, 153, 1)",
        "fill-extrusion-opacity": 0.4,
        "fill-extrusion-vertical-gradient": true,
        "fill-extrusion-base": 2,
        "fill-extrusion-height": 4,
      },
    },
    {
      id: "igensys.buildings_name",
      type: "symbol",
      source: "igensys",
      "source-layer": "buildings_name",

      filter: ["all"],
      layout: {
        "text-field": "{building_n}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 8,
        "text-transform": "none",
        "symbol-placement": "point",
        "text-padding": 5,
        "text-ignore-placement": false,
        "text-justify": "right",
        "icon-text-fit": "both",
        "icon-size": 0.9,
        "text-line-height": 1.2,
      },
      paint: {
        "text-color": "rgba(57, 54, 54, 1)",
        "text-halo-color": "rgba(241, 241, 231, 1)",
        "icon-color": "rgba(198, 20, 20, 1)",
      },
    },
    {
      id: "igensys.poi_bulk",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",

      filter: ["all"],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.6,
        visibility: "visible",
        "text-size": 8,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "icon-image": "dot_11",
        "text-font": ["Open Sans Regular"],
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(0, 0, 0, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_bulk-Fin-copy",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",

      filter: ["all", ["in", "category_i", "4", "5", "6"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 8,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "icon-image": "bank_15",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "top",
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(81, 66, 238, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_bulk_Shopping",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",

      filter: [
        "all",
        [
          "in",
          "category_i",
          "33",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
          "61",
          "67",
          "66",
          "71",
          "89",
        ],
      ],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 8,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "icon-image": "shop_15",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "top",
        "text-padding": 2,
        "text-line-height": 1.2,
      },
      paint: {
        "icon-color": "rgba(190, 6, 119, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-color": "rgba(190, 6, 119, 1)",
        "icon-opacity": 1,
      },
    },
    {
      id: "igensys.poi_bulk_Health",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",

      filter: ["all", ["in", "category_i", "60", "90", "19"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 8,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "top",
        "text-padding": 2,
        "text-line-height": 1.2,
        "icon-image": "hospital_15",
      },
      paint: {
        "icon-color": "rgba(223, 16, 10, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-color": "rgba(223, 16, 10, 1)",
        "icon-opacity": 1,
      },
    },
    {
      id: "igensys.poi_bulk-Food",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",

      filter: ["all", ["in", "category_i", "65", "21", "36"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 8,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "top",
        "text-padding": 2,
        "text-line-height": 1.2,
        "icon-image": "restaurant_15",
      },
      paint: {
        "icon-color": "rgba(238, 182, 34, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-color": "rgba(238, 182, 34, 1)",
        "icon-opacity": 1,
      },
    },
    {
      id: "igensys.poi_quaternary",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",

      filter: ["all"],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.6,
        visibility: "visible",
        "text-size": 8,
        "icon-text-fit": "none",
        "icon-anchor": "top",
        "icon-pitch-alignment": "auto",
        "icon-image": "dot_11",
        "icon-rotation-alignment": "viewport",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(0, 0, 0, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-opacity": 1,
      },
    },
    {
      id: "igensys.poi_quaternary-Fin",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",

      filter: ["all", ["in", "category_i", "4", "5", "6"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 8,
        "icon-text-fit": "none",
        "icon-anchor": "top",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "bank_15",
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(81, 66, 238, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_quaternary-Shopping",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",

      filter: [
        "all",
        [
          "in",
          "category_i",
          "33",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
          "61",
          "67",
          "66",
          "71",
          "89",
        ],
      ],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 8,
        "icon-text-fit": "none",
        "icon-anchor": "top",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "shop_15",
      },
      paint: {
        "icon-color": "rgba(190, 6, 119, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(190, 6, 119, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_quaternary-Health",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",

      filter: ["all", ["in", "category_i", "60", "90", "19"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 8,
        "icon-text-fit": "none",
        "icon-anchor": "top",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "hospital_15",
      },
      paint: {
        "icon-color": "  rgba(223, 16, 10, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "  rgba(223, 16, 10, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_quaternary-Food",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",

      filter: ["all", ["in", "category_i", "65", "21", "36"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 8,
        "icon-text-fit": "none",
        "icon-anchor": "top",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "restaurant_15",
      },
      paint: {
        "icon-color": "rgba(238, 182, 34, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(238, 182, 34, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_tertiary",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",

      filter: ["all"],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-image": "dot_11",
        "icon-size": 0.6,
        visibility: "visible",
        "text-anchor": "top",
        "text-size": 8,
        "icon-anchor": "center",
        "text-font": ["Open Sans Regular"],
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(0, 0, 0, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_tertiary_Fin",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",

      filter: ["all", ["in", "category_i", "4", "5", "6"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 8,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "icon-image": "bank_15",
        "icon-size": 0.8,
        "icon-text-fit": "none",
        "text-ignore-placement": false,
        "text-justify": "auto",
      },
      paint: {
        "text-color": "rgba(81, 66, 238, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_tertiary_Shopping",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",

      filter: [
        "all",
        [
          "in",
          "category_i",
          "33",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
          "61",
          "67",
          "66",
          "71",
          "89",
        ],
      ],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 8,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "icon-image": "bank_15",
        "icon-size": 0.8,
        "icon-text-fit": "none",
        "text-ignore-placement": false,
        "text-justify": "auto",
      },
      paint: {
        "icon-color": "rgba(190, 6, 119, 1)",
        "text-color": "rgba(190, 6, 119, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
      },
    },
    {
      id: "igensys.poi_tertiary_Health",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",

      filter: ["all", ["in", "category_i", "60", "90", "19"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 8,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "icon-image": "hospital_15",
        "icon-size": 0.8,
        "icon-text-fit": "none",
        "text-ignore-placement": false,
        "text-justify": "auto",
      },
      paint: {
        "icon-color": "  rgba(223, 16, 10, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "  rgba(223, 16, 10, 1)",
      },
    },
    {
      id: "igensys.poi_tertiary_Food",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",

      filter: ["all", ["in", "category_i", "65", "21", "36"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 8,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "icon-image": "restaurant_15",
        "icon-size": 0.8,
        "icon-text-fit": "none",
        "text-ignore-placement": false,
        "text-justify": "auto",
      },
      paint: {
        "icon-color": "rgba(238, 182, 34, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(238, 182, 34, 1)",
      },
    },
    {
      id: "igensys.poi_secondary",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",

      filter: ["all"],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.6,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "dot_11",
        "text-size": 8,
        "text-anchor": "top",
        "text-line-height": 1.2,
        "text-justify": "center",
        "text-font": ["Open Sans Regular"],
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-color": "rgba(0, 0, 0, 1)",
      },
    },
    {
      id: "igensys.poi_secondary_Fin",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",

      filter: ["all", ["in", "category_i", "4", "5", "6"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "bank_15",
        "text-size": 8,
        "text-anchor": "top",
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.2,
        "text-padding": 2,
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(81, 66, 238, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_secondary_Shopping",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",

      filter: [
        "all",
        [
          "in",
          "category_i",
          "33",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
          "61",
          "67",
          "66",
          "71",
          "89",
        ],
      ],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "shop_15",
        "text-size": 8,
        "text-anchor": "top",
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.2,
        "text-padding": 2,
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(190, 6, 119, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-color": "rgba(190, 6, 119, 1)",
      },
    },
    {
      id: "igensys.poi_secondary_Health",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",

      filter: ["all", ["in", "category_i", "60", "90", "19"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "hospital_15",
        "text-size": 8,
        "text-anchor": "top",
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.2,
        "text-padding": 2,
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(223, 16, 10, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-color": "rgba(223, 16, 10, 1)",
      },
    },
    {
      id: "igensys.poi_secondary_Food",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",

      filter: ["all", ["in", "category_i", "65", "21", "36"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "restaurant_15",
        "text-size": 8,
        "text-anchor": "top",
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.2,
        "text-padding": 2,
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(238, 182, 34, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-color": "rgba(238, 182, 34, 1)",
      },
    },
    {
      id: "igensys.poi_primary",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",

      filter: ["all"],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.7,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 8,
        "text-line-height": 1.2,
        "icon-image": "dot_11",
      },
      paint: {
        "icon-color": "rgba(116, 140, 225, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_primary-Fin",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",

      filter: ["all", ["in", "category_i", "4", "5", "6"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 8,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-image": "bank_15",
      },
      paint: {
        "icon-color": "rgba(147, 54, 78, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(81, 66, 238, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_primary-Shopping",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",

      filter: [
        "all",
        [
          "in",
          "category_i",
          "33",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
          "61",
          "67",
          "66",
          "71",
          "89",
        ],
      ],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 8,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-image": "shop_15",
      },
      paint: {
        "icon-color": "rgba(190, 6, 119, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(190, 6, 119, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_primary-Health",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",

      filter: ["all", ["in", "category_i", "60", "90", "19"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 8,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-image": "hospital_15",
      },
      paint: {
        "icon-color": "rgba(223, 16, 10, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(223, 16, 10, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_primary-Food",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",

      filter: ["all", ["in", "category_i", "65", "21", "36"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 8,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-image": "restaurant_15",
      },
      paint: {
        "icon-color": "rgba(238, 182, 34, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(238, 182, 34, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "landuse_urban_name",
      type: "symbol",
      source: "igensys",
      "source-layer": "landuse_urban",

      filter: ["all"],
      layout: {
        "text-field": "{name}",
        "icon-size": 0.7,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular", "Arial Unicode MS Regular"],
        "text-size": 8,
        "text-line-height": 1.2,
      },
      paint: {
        "icon-color": "rgba(116, 140, 225, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(10, 9, 9, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "landuse_industrial_name",
      type: "symbol",
      source: "igensys",
      "source-layer": "landuse_industrial_name",

      filter: ["all"],
      layout: {
        "text-field": "{name}",
        "icon-size": 0.7,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular", "Arial Unicode MS Regular"],
        "text-size": 8,
        "text-line-height": 1.2,
      },
      paint: {
        "icon-color": "rgba(116, 140, 225, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(10, 9, 9, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.water_large_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "water_large_name",

      filter: ["all"],
      layout: {
        "text-field": "{name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "symbol-placement": "point",
        "text-padding": 2,
        "icon-size": 1.2,
        "icon-pitch-alignment": "auto",
        "text-size": 8,
      },
      paint: {
        "text-color": "rgba(55, 42, 239, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(240, 237, 228, 1)",
        "text-halo-width": 0.5,
      },
    },
    {
      id: "landuse_green_name",
      type: "symbol",
      source: "igensys",
      "source-layer": "landuse_green_name",

      filter: ["all"],
      layout: {
        "text-field": "{name}",
        "icon-size": 0.7,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "center",
        "text-font": ["Cabin Semi Bold"],
        "text-line-height": 1.2,
        "text-allow-overlap": true,
        "text-ignore-placement": false,
        "text-pitch-alignment": "map",
        "text-rotation-alignment": "map",
        "icon-text-fit": "both",
        "text-size": 9,
      },
      paint: {
        "icon-color": "rgba(116, 140, 225, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "icon-opacity": 1,
        "text-opacity": 0.8,
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.road_major_urban_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_major_urban",

      filter: ["all"],
      layout: {
        "text-field": "{street_nam}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 1.2,
        visibility: "visible",
        "symbol-placement": "line",
        "text-size": 7,
        "text-line-height": 1.2,
        "text-font": ["Arial Unicode MS Regular"],
      },
      paint: {
        "icon-color": "rgba(188, 195, 227, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(5, 4, 4, 1)",
        "text-opacity": 1,
      },
    },
    {
      id: "igensys.road_major_district_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_major_district",

      filter: ["all"],
      layout: {
        "text-field": "{street_nam}",
        "text-size": 8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 1.2,
        visibility: "visible",
        "symbol-placement": "line",
        "text-font": ["Arial Unicode MS Regular"],
      },
      paint: {
        "icon-color": "rgba(188, 195, 227, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(5, 4, 4, 1)",
        "text-opacity": 1,
      },
    },
    {
      id: "igensys.road_state_highway_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_state_highways",

      filter: ["all"],
      layout: {
        "text-field": "{street_nam}",
        "text-size": 8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 1.2,
        visibility: "visible",
        "symbol-placement": "line",
        "text-font": ["Arial Unicode MS Regular"],
      },
      paint: {
        "icon-color": "rgba(188, 195, 227, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(5, 4, 4, 1)",
        "text-opacity": 1,
      },
    },
    {
      id: "igensys.road_national_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_national_highways",

      filter: ["all"],
      layout: {
        "text-field": "{street_nam}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "symbol-placement": "line",
        "text-size": 9,
        "text-font": ["Arial Unicode MS Regular"],
      },
      paint: {
        "icon-color": "rgba(188, 195, 227, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(89, 66, 48, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(231, 215, 215, 1)",
      },
    },
    {
      id: "igensys.admin_5_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "admin_boundary_name_5",

      filter: ["all"],
      layout: {
        "text-field": "{admin_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-pitch-alignment": "auto",
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "text-transform": "uppercase",
        "text-font": ["Cabin Regular"],
        "text-size": 11,
        "text-variable-anchor": ["top"],
        "text-allow-overlap": false,
        "text-justify": "auto",
        "text-anchor": "top",
      },
      paint: {
        "icon-color": "rgba(205, 212, 233, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(0, 0, 0, 1)",
        "text-translate-anchor": "map",
        "icon-translate-anchor": "map",
        "icon-opacity": 1,
        "text-opacity": 1,
        "text-halo-color": "rgba(241, 234, 234, 1)",
      },
    },
    {
      id: "igensys.admin_4_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "admin_boundary_name_4",

      filter: ["all"],
      layout: {
        "text-field": "{admin_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 11,
        "icon-pitch-alignment": "auto",
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "text-justify": "auto",
        "text-anchor": "top",
        "text-keep-upright": false,
        "text-transform": "uppercase",
        "text-font": ["Cabin Regular"],
      },
      paint: {
        "icon-color": "rgba(205, 212, 233, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(6, 5, 5, 1)",
        "text-translate-anchor": "map",
        "icon-translate-anchor": "map",
        "icon-opacity": 1,
        "text-opacity": 1,
        "text-halo-color": "rgba(241, 234, 234, 1)",
      },
    },
    {
      id: "igensys.admin_3_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "admin_boundary_name_3",

      filter: ["all"],
      layout: {
        "text-field": "{admin_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-size": 0.5,
        "icon-pitch-alignment": "auto",
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "text-justify": "auto",
        "text-anchor": "top",
        "text-font": ["Cabin Regular"],
        "text-transform": "uppercase",
        "text-size": 12,
      },
      paint: {
        "icon-color": "rgba(205, 212, 233, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(6, 5, 5, 1)",
        "text-translate-anchor": "map",
        "icon-translate-anchor": "map",
        "icon-opacity": 1,
        "text-opacity": 1,
        "text-halo-color": "rgba(241, 234, 234, 1)",
      },
    },
    {
      id: "igensys.admin_2_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "admin_boundary_name_2",

      filter: ["all"],
      layout: {
        "text-field": "{admin_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 12,
        "text-allow-overlap": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "symbol-z-order": "auto",
        "text-justify": "auto",
        "icon-optional": false,
        "text-anchor": "top",
        "text-font": ["Cabin Regular"],
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": "rgba(6, 5, 5, 1)",
        "text-translate-anchor": "map",
        "icon-translate-anchor": "map",
        "text-halo-color": "rgba(241, 234, 234, 1)",
        "text-halo-width": 2,
        "text-opacity": 1,
      },
    },
  ],
  id: "osm-liberty",
};
