export default {
  version: 8,
  name: "OSM Liberty",
  metadata: {
    "maputnik:license":
      "https://github.com/maputnik/osm-liberty/blob/gh-pages/LICENSE.md",
    "maputnik:renderer": "mbgljs",
    "openmaptiles:version": "3.x",
  },
  sources: {
    igensys: {
      type: "vector",
      tiles: ["https://alpha.tiles.unl.global/v2alpha/vector/767/{z}/{x}/{y}"],
      minzoom: 3,
      maxzoom: 18,
    },
  },
  sprite: "https://maputnik.github.io/osm-liberty/sprites/osm-liberty",
  glyphs:
    "https://api.maptiler.com/fonts/{fontstack}/{range}.pbf?key=xCp8xgPeanjDKCXNoO4B",
  layers: [
    {
      id: "background",
      type: "background",
      paint: { "background-color": "rgb(239,239,239)" },
    },
    {
      id: "igensys.admin_boundary5",
      type: "fill",
      source: "igensys",
      "source-layer": "admin_boundary_5",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(239,239,239)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.admin_boundary4",
      type: "fill",
      source: "igensys",
      "source-layer": "admin_boundary_4",
      minzoom: 12,
      maxzoom: 18,
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(239,239,239)", "fill-opacity": 0.6 },
    },
    {
      id: "igensys.admin_boundary3",
      type: "fill",
      source: "igensys",
      "source-layer": "admin_boundary_3",
      minzoom: 10,
      maxzoom: 12,
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(239,239,239)", "fill-opacity": 0.9 },
    },
    {
      id: "igensys.admin_boundary2",
      type: "fill",
      source: "igensys",
      "source-layer": "admin_boundary_2",
      minzoom: 8,
      maxzoom: 10,
      filter: ["all"],
      layout: { visibility: "visible" },
      paint: {
        "fill-translate-anchor": "viewport",
        "fill-opacity": 0.9,
        "fill-color": "rgba(229, 229, 229, 1)",
      },
    },
    {
      id: "igensys.landuse-Industrial_Air",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_industrial",
      minzoom: 8,
      maxzoom: 20,
      filter: [
        "any",
        ["==", "name", "Chhatrapati Shivaji International Airport"],
        ["==", "name", "Juhu Domestic Airport"],
      ],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgba(213, 200, 200, 1)", "fill-opacity": 0.6 },
    },
    {
      id: "igensys.landuse-Industrial",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_industrial",
      minzoom: 12,
      maxzoom: 24,
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgba(218, 198, 198, 1)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.landuse_urban-Health",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_urban",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all", ["in", "type", "Hospital"]],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgba(213, 170, 166, 1)", "fill-opacity": 0.6 },
    },
    {
      id: "igensys.landuse_urban-Edu",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_urban",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all", ["in", "type", "Education Facility"]],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(222,215,211)", "fill-opacity": 0.6 },
    },
    {
      id: "igensys.landuse_urban",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_urban",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(224,226,235)", "fill-opacity": 0.6 },
    },
    {
      id: "igensys.landuse_urban_Park",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_urban",
      minzoom: 14,
      maxzoom: 24,
      filter: [
        "any",
        ["in", "type", "Park"],
        ["in", "type", "parking_area"],
        ["in", "type", "Forest Area"],
        ["in", "type", "Golf Course"],
        ["==", "name", "Azad Maidan"],
        ["==", "name", "Oval Maidan"],
      ],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgba(139, 223, 155, 1)", "fill-opacity": 0.6 },
    },
    {
      id: "igensys.landuse_Others",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_Others",
      minzoom: 12,
      maxzoom: 18,
      filter: ["all", ["==", "type", ""]],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgba(156, 239, 239, 1)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.landuse-green",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_green",
      minzoom: 3,
      maxzoom: 18,
      filter: ["all"],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgba(139, 223, 155, 1)", "fill-opacity": 0.8 },
    },
    {
      id: "igensys.landuse_hydro",
      type: "fill",
      source: "igensys",
      "source-layer": "landuse_hydro",
      minzoom: 10,
      maxzoom: 18,
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(156,192,249)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.water_small",
      type: "fill",
      source: "igensys",
      "source-layer": "water_medium",
      minzoom: 16,
      maxzoom: 24,
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(156,192,249)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.water_medium",
      type: "fill",
      source: "igensys",
      "source-layer": "water_medium",
      minzoom: 16,
      maxzoom: 24,
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(156,192,249)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.water_large",
      type: "fill",
      source: "igensys",
      "source-layer": "water_large",
      minzoom: 8,
      maxzoom: 24,
      filter: ["all", ["==", "name", ""]],
      layout: { visibility: "visible" },
      paint: { "fill-color": "rgb(156,192,249)", "fill-opacity": 0.5 },
    },
    {
      id: "igensys.rail_mini_rail",
      type: "line",
      source: "igensys",
      "source-layer": "mini_rail",
      minzoom: 12,
      maxzoom: 24,
      layout: { visibility: "visible" },
      paint: {
        "line-opacity": 1,
        "line-color": "rgba(16, 15, 15, 1)",
        "line-width": 1.2,
        "line-blur": 1.3,
        "line-dasharray": [2, 2],
      },
    },
    {
      id: "igensys.rail_metro_rail",
      type: "line",
      source: "igensys",
      "source-layer": "metro_rail",
      minzoom: 12,
      maxzoom: 24,
      layout: { visibility: "visible" },
      paint: {
        "line-opacity": 1,
        "line-color": "rgba(16, 15, 15, 1)",
        "line-width": 1.2,
        "line-blur": 1.2,
        "line-dasharray": [2, 2],
      },
    },
    {
      id: "igensys.rail_mono_rail",
      type: "line",
      source: "igensys",
      "source-layer": "mono_rail",
      minzoom: 12,
      maxzoom: 24,
      layout: { visibility: "visible" },
      paint: {
        "line-opacity": 1,
        "line-color": "rgba(16, 15, 15, 1)",
        "line-width": 1.5,
        "line-blur": 1.5,
        "line-dasharray": [2, 2],
      },
    },
    {
      id: "igensys.rail_railroad",
      type: "line",
      source: "igensys",
      "source-layer": "railroad",
      minzoom: 12,
      maxzoom: 24,
      layout: {
        visibility: "visible",
        "line-miter-limit": 2,
        "line-round-limit": 1.06,
      },
      paint: {
        "line-color": "rgba(16, 15, 15, 1)",
        "line-opacity": 1,
        "line-blur": 1.9,
        "line-dasharray": [2, 2],
        "line-width": 1.5,
      },
    },
    {
      id: "igensys.road_minor",
      type: "line",
      source: "igensys",
      "source-layer": "road_minor",
      minzoom: 12,
      maxzoom: 24,
      filter: ["all"],
      layout: { visibility: "visible" },
      paint: {
        "line-color": "rgba(255, 255, 255, 1)",
        "line-width": 1.6,
        "line-opacity": 0.9,
      },
    },
    {
      id: "igensys.road_private",
      type: "line",
      source: "igensys",
      "source-layer": "road_private",
      minzoom: 12,
      maxzoom: 24,
      layout: { visibility: "visible" },
      paint: { "line-color": "rgba(255, 255, 255, 1)", "line-opacity": 1 },
    },
    {
      id: "igensys.road_major_Urban",
      type: "line",
      source: "igensys",
      "source-layer": "road_major_urban",
      minzoom: 10,
      maxzoom: 24,
      filter: ["all"],
      layout: { visibility: "visible" },
      paint: {
        "line-opacity": 1,
        "line-gap-width": 1.5,
        "line-width": 1.5,
        "line-blur": 1,
        "line-color": "rgba(255, 251, 251, 1)",
      },
    },
    {
      id: "igensys.road_major_district",
      type: "line",
      source: "igensys",
      "source-layer": "road_major_district",
      minzoom: 10,
      maxzoom: 24,
      filter: ["all"],
      layout: { visibility: "visible" },
      paint: {
        "line-color": "rgba(255, 251, 251, 1)",
        "line-gap-width": 1,
        "line-offset": 0,
        "line-width": 1,
        "line-opacity": 1,
      },
    },
    {
      id: "igensys.road_state_highways",
      type: "line",
      source: "igensys",
      "source-layer": "road_state_highways",
      minzoom: 2,
      maxzoom: 24,
      layout: {
        visibility: "visible",
        "line-join": "bevel",
        "line-cap": "butt",
      },
      paint: {
        "line-color": "rgba(255, 222, 65, 1)",
        "line-gap-width": 1,
        "line-opacity": 1,
        "line-width": 1,
      },
    },
    {
      id: "igensys.road_national_highways",
      type: "line",
      source: "igensys",
      "source-layer": "road_national_highways",
      minzoom: 2,
      maxzoom: 24,
      filter: ["all"],
      layout: { visibility: "visible" },
      paint: {
        "line-color": "rgba(247, 232, 106, 1)",
        "line-gap-width": 1,
        "line-opacity": 1,
        "line-width": 1.5,
      },
    },
    {
      id: "igensys.rail_railway_station",
      type: "symbol",
      source: "igensys",
      "source-layer": "railway_station",
      minzoom: 13,
      maxzoom: 18,
      filter: ["all"],
      layout: {
        "text-field": "{station_name}",
        visibility: "visible",
        "text-size": 8.5,
        "icon-allow-overlap": false,
        "icon-size": 0.7,
        "icon-text-fit": "none",
        "text-max-width": 1,
        "text-justify": "auto",
        "text-anchor": "top",
        "icon-image": "ranger_station_15",
        "icon-anchor": "bottom",
      },
      paint: { "text-color": "rgba(48, 10, 10, 1)" },
    },
    {
      id: "Building_3D",
      type: "fill-extrusion",
      source: "igensys",
      "source-layer": "buildings",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all"],
      layout: { visibility: "visible" },
      paint: {
        "fill-extrusion-color": "rgba(188, 180, 180, 1)",
        "fill-extrusion-opacity": 0.4,
        "fill-extrusion-vertical-gradient": true,
        "fill-extrusion-base": 2,
        "fill-extrusion-height": 4,
      },
    },
    {
      id: "igensys.buildings_name",
      type: "symbol",
      source: "igensys",
      "source-layer": "buildings_name",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{building_n}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 8,
        "text-transform": "none",
        "symbol-placement": "point",
        "text-ignore-placement": false,
        "text-justify": "right",
        "icon-text-fit": "both",
        "icon-size": 0.9,
        "text-line-height": 1.2,
        "text-padding": 5,
      },
      paint: {
        "text-color": "rgba(57, 54, 54, 1)",
        "text-halo-color": "rgba(241, 241, 231, 1)",
        "icon-color": "rgba(198, 20, 20, 1)",
      },
    },
    {
      id: "igensys.poi_bulk",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.6,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "icon-image": "dot_11",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(38, 38, 153, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(0, 0, 0, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_bulk-Govt",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "15", "14"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.6,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "icon-image": "embassy_15",
      },
      paint: {
        "icon-color": "rgba(38, 38, 153, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(99, 13, 13, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_bulk-Fin-copy",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "4", "5", "6"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "icon-image": "bank_15",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(33, 14, 231, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_bulk_Shopping",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",
      minzoom: 17,
      maxzoom: 24,
      filter: [
        "all",
        [
          "in",
          "category_i",
          "33",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
          "61",
          "67",
          "66",
          "71",
          "89",
        ],
      ],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "icon-image": "shop_15",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "text-padding": 2,
        "text-line-height": 1.2,
      },
      paint: {
        "icon-color": "rgba(190, 6, 119, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-color": "rgba(190, 6, 119, 1)",
        "icon-opacity": 1,
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_bulk_Health",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "60", "90", "19"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "text-padding": 2,
        "text-line-height": 1.2,
        "icon-image": "hospital_15",
      },
      paint: {
        "icon-color": "rgba(223, 16, 10, 1)",
        "icon-halo-color": "rgba(223, 16, 10, 1)",
        "text-color": "rgba(223, 16, 10, 1)",
        "icon-opacity": 1,
        "text-halo-width": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.poi_bulk-Food-copy",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "65", "21", "36"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "text-padding": 2,
        "text-line-height": 1.2,
        "icon-image": "restaurant_15",
      },
      paint: {
        "icon-color": "rgba(238, 182, 34, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-color": "rgba(155, 66, 5, 1)",
        "icon-opacity": 1,
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_bulk-Food",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "65", "21", "36"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "text-padding": 2,
        "text-line-height": 1.2,
        "icon-image": "restaurant_15",
      },
      paint: {
        "icon-color": "rgba(238, 182, 34, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-color": "rgba(155, 66, 5, 1)",
        "icon-opacity": 1,
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_bulk-Rec",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "2", "7", "18", "26"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "text-padding": 2,
        "text-line-height": 1.2,
        "icon-image": "attraction_15",
      },
      paint: {
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-opacity": 1,
        "text-color": "rgba(3, 71, 21, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_bulk-Hotel",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "20"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "text-padding": 2,
        "text-line-height": 1.2,
        "icon-image": "town_hall_15",
      },
      paint: {
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-opacity": 1,
        "text-color": "rgba(245, 9, 107, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_bulk-Pow",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", 29]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "text-padding": 2,
        "text-line-height": 1.2,
        "icon-image": "place_of_worship_15",
      },
      paint: {
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-opacity": 1,
        "text-color": "rgba(227, 74, 11, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_bulk-Pow-Auto",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "3"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "text-padding": 2,
        "text-line-height": 1.2,
        "icon-image": "car_15",
      },
      paint: {
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-opacity": 1,
        "text-color": "rgba(57, 57, 78, 1)",
        "text-halo-width": 1,
        "icon-color": "rgba(57, 57, 78, 1)",
      },
    },
    {
      id: "igensys.poi_bulk-Pow-Edu",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_bulk",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "17", "22"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "text-padding": 2,
        "text-line-height": 1.2,
        "icon-image": "college_15",
      },
      paint: {
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-opacity": 1,
        "text-color": "rgba(36, 60, 3, 1)",
        "text-halo-width": 1,
        "icon-color": "rgba(136, 240, 8, 1)",
      },
    },
    {
      id: "igensys.poi_quaternary",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.6,
        visibility: "visible",
        "text-size": 10,
        "icon-text-fit": "none",
        "icon-anchor": "bottom",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "viewport",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "dot_11",
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(0, 0, 0, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-opacity": 1,
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_quaternary-Govt",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "15", "14"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.6,
        visibility: "visible",
        "text-size": 10,
        "icon-text-fit": "none",
        "icon-anchor": "bottom",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "viewport",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "embassy_15",
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(99, 13, 13, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-opacity": 1,
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_quaternary-Fin",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "4", "5", "6"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 9,
        "icon-text-fit": "none",
        "icon-anchor": "bottom",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "bank_15",
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(33, 14, 231, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_quaternary-Shopping",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",
      minzoom: 16,
      maxzoom: 24,
      filter: [
        "all",
        [
          "in",
          "category_i",
          "33",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
          "61",
          "67",
          "66",
          "71",
          "89",
        ],
      ],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "icon-text-fit": "none",
        "icon-anchor": "bottom",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "shop_15",
      },
      paint: {
        "icon-color": "rgba(190, 6, 119, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(190, 6, 119, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_quaternary-Health",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "60", "90", "19"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "icon-text-fit": "none",
        "icon-anchor": "bottom",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "hospital_15",
      },
      paint: {
        "icon-color": "  rgba(223, 16, 10, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "  rgba(223, 16, 10, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_quaternary-Food",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "65", "21", "36"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "icon-text-fit": "none",
        "icon-anchor": "bottom",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "restaurant_15",
      },
      paint: {
        "icon-color": "rgba(238, 182, 34, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(155, 66, 5, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_quaternary-Rec",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "2", "7", "18", "26"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "icon-text-fit": "none",
        "icon-anchor": "bottom",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "attraction_15",
      },
      paint: {
        "icon-color": "rgba(238, 182, 34, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(3, 71, 21, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_quaternary-Hotel",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "20"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "icon-text-fit": "none",
        "icon-anchor": "bottom",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "town_hall_15",
      },
      paint: {
        "icon-color": "rgba(245, 9, 107, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(245, 9, 107, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_quaternary-Pow",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "29"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "icon-text-fit": "none",
        "icon-anchor": "bottom",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "place_of_worship_15",
      },
      paint: {
        "icon-color": "rgba(245, 9, 107, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(227, 74, 11, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_quaternary-Auto",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "3"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "icon-text-fit": "none",
        "icon-anchor": "bottom",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "car_15",
      },
      paint: {
        "icon-color": "rgba(57, 57, 78, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(57, 57, 78, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_quaternary-Edu",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_quaternary",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "17", "22"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.8,
        visibility: "visible",
        "text-size": 10,
        "icon-text-fit": "none",
        "icon-anchor": "bottom",
        "icon-pitch-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "icon-rotate": 0,
        "icon-keep-upright": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
        "icon-image": "college_15",
      },
      paint: {
        "icon-color": "rgba(136, 240, 8, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(36, 60, 3, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_tertiary",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-image": "dot_11",
        "icon-size": 0.6,
        visibility: "visible",
        "text-anchor": "top",
        "text-size": 10,
        "icon-anchor": "bottom",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(0, 0, 0, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_tertiary-Govt",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "15", "14"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-image": "embassy_15",
        "icon-size": 0.6,
        visibility: "visible",
        "text-anchor": "top",
        "text-size": 10,
        "icon-anchor": "bottom",
        "text-font": ["Open Sans Regular"],
        "text-justify": "auto",
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(99, 13, 13, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_tertiary_Fin",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "4", "5", "6"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "icon-image": "bank_15",
        "icon-size": 0.8,
        "icon-text-fit": "none",
        "text-ignore-placement": false,
        "text-justify": "auto",
        "icon-anchor": "bottom",
      },
      paint: {
        "text-color": "rgba(33, 14, 231, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_tertiary_Shopping",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",
      minzoom: 15,
      maxzoom: 24,
      filter: [
        "all",
        [
          "in",
          "category_i",
          "33",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
          "61",
          "67",
          "66",
          "71",
          "89",
        ],
      ],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "icon-image": "bank_15",
        "icon-size": 0.8,
        "icon-text-fit": "none",
        "text-ignore-placement": false,
        "text-justify": "auto",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(190, 6, 119, 1)",
        "text-color": "rgba(190, 6, 119, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_tertiary_Health",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "60", "90", "19"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "icon-image": "hospital_15",
        "icon-size": 0.8,
        "icon-text-fit": "none",
        "text-ignore-placement": false,
        "text-justify": "auto",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "  rgba(223, 16, 10, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "  rgba(223, 16, 10, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_tertiary_Food",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "65", "21", "36"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "icon-image": "restaurant_15",
        "icon-size": 0.8,
        "icon-text-fit": "none",
        "text-ignore-placement": false,
        "text-justify": "auto",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(238, 182, 34, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(155, 66, 5, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_tertiary_Rec",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "2", "7", "18", "26"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "icon-image": "attraction_15",
        "icon-size": 0.8,
        "icon-text-fit": "none",
        "text-ignore-placement": false,
        "text-justify": "auto",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(238, 182, 34, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(3, 71, 21, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_tertiary-Hotel",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "20"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "icon-image": "town_hall_15",
        "icon-size": 0.8,
        "icon-text-fit": "none",
        "text-ignore-placement": false,
        "text-justify": "auto",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(245, 9, 107, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(245, 9, 107, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_tertiary-Pow",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "29"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "icon-image": "place_of_worship_15",
        "icon-size": 0.8,
        "icon-text-fit": "none",
        "text-ignore-placement": false,
        "text-justify": "auto",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(245, 9, 107, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(227, 74, 11, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_tertiary-Auto",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "3"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "icon-image": "place_of_worship_15",
        "icon-size": 0.8,
        "icon-text-fit": "none",
        "text-ignore-placement": false,
        "text-justify": "auto",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(57, 57, 78, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(57, 57, 78, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_tertiary-Edu",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_tertiary",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "17", "22"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 10,
        "symbol-avoid-edges": true,
        "symbol-z-order": "auto",
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "icon-image": "college_15",
        "icon-size": 0.8,
        "icon-text-fit": "none",
        "text-ignore-placement": false,
        "text-justify": "auto",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(136, 240, 8, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "text-color": "rgba(36, 60, 3, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_secondary",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.6,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "dot_11",
        "text-size": 10,
        "text-anchor": "top",
        "text-line-height": 1.2,
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_secondary-Govt",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "15", "14"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.6,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "embassy_15",
        "text-size": 10,
        "text-anchor": "top",
        "text-line-height": 1.2,
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(21, 21, 22, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "icon-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-color": "rgba(99, 13, 13, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_secondary_Fin",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "4", "5", "6"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "bank_15",
        "text-size": 10,
        "text-anchor": "top",
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.2,
        "text-padding": 2,
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(33, 14, 231, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_secondary_Shopping",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",
      minzoom: 14,
      maxzoom: 24,
      filter: [
        "all",
        [
          "in",
          "category_i",
          "33",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
          "61",
          "67",
          "66",
          "71",
          "89",
        ],
      ],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "shop_15",
        "text-size": 10,
        "text-anchor": "top",
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.2,
        "text-padding": 2,
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(190, 6, 119, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-color": "rgba(190, 6, 119, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_secondary_Health",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "60", "90", "19"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "hospital_15",
        "text-size": 10,
        "text-anchor": "top",
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.2,
        "text-padding": 2,
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(223, 16, 10, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-color": "rgba(223, 16, 10, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_secondary_Food",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "65", "21", "36"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "restaurant_15",
        "text-size": 10,
        "text-anchor": "top",
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.2,
        "text-padding": 2,
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(155, 66, 5, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-color": "rgba(238, 182, 34, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_secondary-Rec",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "2", "7", "18", "26"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "attraction_15",
        "text-size": 10,
        "text-anchor": "top",
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.2,
        "text-padding": 2,
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(7, 142, 142, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-color": "rgba(238, 182, 34, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_secondary-Hotel",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "20"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "town_hall_15",
        "text-size": 10,
        "text-anchor": "top",
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.2,
        "text-padding": 2,
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(245, 9, 107, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-color": "rgba(245, 9, 107, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_secondary-Pow",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "29"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "place_of_worship_15",
        "text-size": 10,
        "text-anchor": "top",
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.2,
        "text-padding": 2,
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(227, 74, 11, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-color": "rgba(245, 9, 107, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_secondary-Auto",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "3"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-image": "car_15",
        "text-size": 10,
        "text-anchor": "top",
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.2,
        "text-padding": 2,
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(57, 57, 78, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-color": "rgba(57, 57, 78, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_secondary-Edu",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_secondary",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "17", "22"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 10,
        "text-anchor": "top",
        "text-justify": "auto",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.2,
        "text-padding": 2,
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(36, 60, 3, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "icon-color": "rgba(136, 240, 8, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_primary",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",
      minzoom: 13,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.7,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 10,
        "text-line-height": 1.2,
        "icon-image": "dot_11",
        "icon-anchor": "bottom",
        "text-justify": "auto",
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_primary-Govt",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",
      minzoom: 13,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "15", "14"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.7,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 10,
        "text-line-height": 1.2,
        "icon-image": "embassy_15",
        "icon-anchor": "bottom",
        "text-justify": "auto",
      },
      paint: {
        "icon-opacity": 1,
        "text-color": "rgba(99, 13, 13, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_primary-Fin",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",
      minzoom: 13,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "4", "5", "6"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 10,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-image": "bank_15",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(147, 54, 78, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(33, 14, 231, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_primary-Shopping",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",
      minzoom: 13,
      maxzoom: 24,
      filter: [
        "all",
        [
          "in",
          "category_i",
          "33",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
          "61",
          "67",
          "66",
          "71",
          "89",
        ],
      ],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 10,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-image": "shop_15",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(190, 6, 119, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(190, 6, 119, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_primary-Health",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",
      minzoom: 13,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "60", "90", "19"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.6,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 10,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "icon-image": "hospital_15",
      },
      paint: {
        "icon-color": "rgba(223, 16, 10, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(223, 16, 10, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_primary-Food",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",
      minzoom: 13,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "65", "21", "36"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 10,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-image": "restaurant_15",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(238, 182, 34, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(155, 66, 5, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_primary-Rec",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",
      minzoom: 13,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "2", "7", "18", "26"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 10,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-image": "attraction_15",
        "icon-anchor": "bottom",
      },
      paint: {
        "icon-color": "rgba(238, 182, 34, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(7, 142, 142, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_primary-Hotel",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",
      minzoom: 13,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "20"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 10,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "icon-image": "town_hall_15",
      },
      paint: {
        "icon-color": "rgba(245, 9, 107, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(245, 9, 107, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_primary-Pow",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",
      minzoom: 13,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "29"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 10,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "icon-image": "place_of_worship_15",
      },
      paint: {
        "icon-color": "rgba(245, 9, 107, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(227, 74, 11, 1)",
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
      },
    },
    {
      id: "igensys.poi_primary-Auto",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",
      minzoom: 13,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "3"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 10,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "icon-image": "car_15",
      },
      paint: {
        "icon-color": "rgba(57, 57, 78, 1)",
        "icon-opacity": 1,
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
        "text-color": "rgba(57, 57, 78, 1)",
      },
    },
    {
      id: "igensys.poi_primary-Prior",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",
      minzoom: 10,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "17", "22"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 10,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "icon-image": "college_15",
      },
      paint: {
        "icon-color": "rgba(136, 240, 8, 1)",
        "icon-opacity": 1,
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
        "text-color": "rgba(36, 60, 3, 1)",
      },
    },
    {
      id: "igensys.poi_primary-Edu",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",
      minzoom: 13,
      maxzoom: 24,
      filter: ["all", ["in", "category_i", "17", "22"]],
      layout: {
        "text-field": "{poi_name}",
        "icon-size": 0.8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-size": 10,
        "text-line-height": 1.2,
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "icon-image": "college_15",
      },
      paint: {
        "icon-color": "rgba(136, 240, 8, 1)",
        "icon-opacity": 1,
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
        "text-color": "rgba(36, 60, 3, 1)",
      },
    },
    {
      id: "igensys.poi_primary-P1",
      type: "symbol",
      source: "igensys",
      "source-layer": "poi_primary",
      minzoom: 10,
      maxzoom: 24,
      filter: [
        "all",
        [
          "in",
          "category_i",
          "1",
          "4",
          "2",
          "487",
          "488",
          "502",
          "505",
          "504",
          "120",
          "119",
        ],
      ],
      layout: {
        "text-field": "{poi_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular"],
        "text-line-height": 1.5,
        "text-justify": "auto",
        "icon-anchor": "bottom",
        "text-padding": 2,
        "text-size": 9,
        "icon-size": 2,
        "text-keep-upright": false,
      },
      paint: {
        "icon-color": "rgba(136, 240, 8, 1)",
        "icon-opacity": 1,
        "text-opacity": 1,
        "text-halo-color": "hsl(0, 0%, 100%)",
        "text-halo-width": 1,
        "text-color": "rgba(107, 2, 102, 1)",
      },
    },
    {
      id: "landuse_urban_name",
      type: "symbol",
      source: "igensys",
      "source-layer": "landuse_urban_name",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{name}",
        "icon-size": 0.7,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular", "Arial Unicode MS Regular"],
        "text-size": 8,
        "text-line-height": 1.2,
      },
      paint: {
        "icon-color": "rgba(116, 140, 225, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(10, 9, 9, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "landuse_industrial_name",
      type: "symbol",
      source: "igensys",
      "source-layer": "landuse_industrial_name",
      minzoom: 12,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{name}",
        "icon-size": 0.7,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "top",
        "text-font": ["Open Sans Regular", "Arial Unicode MS Regular"],
        "text-size": 8,
        "text-line-height": 1.2,
      },
      paint: {
        "icon-color": "rgba(116, 140, 225, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "icon-opacity": 1,
        "text-color": "rgba(10, 9, 9, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.water_Hydro",
      type: "symbol",
      source: "igensys",
      "source-layer": "landuse_hydro_name",
      minzoom: 18,
      maxzoom: 20,
      filter: ["all"],
      layout: {
        "text-field": "{name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "symbol-placement": "point",
        "icon-size": 1.2,
        "icon-pitch-alignment": "auto",
        "text-size": 8,
        "text-justify": "auto",
        "text-anchor": "top",
        "text-padding": 8,
        "text-line-height": 1.2,
        "text-max-width": 5,
      },
      paint: {
        "text-color": "rgba(55, 42, 239, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(240, 237, 228, 1)",
        "text-halo-width": 0.5,
      },
    },
    {
      id: "igensys.water_large_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "water_large_name",
      minzoom: 11,
      maxzoom: 20,
      filter: [
        "all",
        ["!=", "name", "Mithi River"],
        ["!=", "name", "Malad Creek"],
        ["!=", "name", "Belapur Holding Pond"],
        ["!=", "name", "Lotus Pond"],
        ["!=", "name", "Mahim River"],
      ],
      layout: {
        "text-field": "{name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "symbol-placement": "point",
        "text-padding": 2,
        "icon-size": 1.2,
        "icon-pitch-alignment": "auto",
        "text-size": 8,
      },
      paint: {
        "text-color": "rgba(55, 42, 239, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(240, 237, 228, 1)",
        "text-halo-width": 0.5,
      },
    },
    {
      id: "igensys.hydro_line",
      type: "symbol",
      source: "igensys",
      "source-layer": "hydro_line",
      minzoom: 11,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": true,
        visibility: "visible",
        "symbol-placement": "line",
        "text-size": 9,
        "text-font": ["Arial Unicode MS Regular"],
        "icon-text-fit": "none",
        "icon-optional": true,
        "icon-rotation-alignment": "auto",
        "symbol-spacing": 250,
        "text-allow-overlap": false,
        "text-ignore-placement": true,
        "symbol-avoid-edges": true,
        "text-justify": "auto",
        "text-anchor": "right",
        "text-keep-upright": false,
        "text-optional": false,
        "icon-anchor": "center",
        "icon-keep-upright": false,
        "text-variable-anchor": ["center"],
        "text-radial-offset": 0,
        "icon-text-fit-padding": [2, 2, 2, 2],
        "icon-size": 2,
        "symbol-z-order": "auto",
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "text-writing-mode": ["horizontal", "vertical"],
        "text-offset": [2, 2],
      },
      paint: {
        "icon-color": "rgba(1, 1, 27, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(130, 117, 107, 1)",
        "text-halo-color": "rgba(233, 224, 224, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
      },
    },
    {
      id: "landuse_green_name",
      type: "symbol",
      source: "igensys",
      "source-layer": "landuse_green_name",
      minzoom: 8,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{name}",
        "icon-size": 0.7,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-padding": 2,
        "text-anchor": "center",
        "text-font": ["Cabin Semi Bold"],
        "text-line-height": 1.2,
        "text-allow-overlap": true,
        "text-ignore-placement": false,
        "text-pitch-alignment": "map",
        "text-rotation-alignment": "map",
        "icon-text-fit": "both",
        "text-size": 9,
      },
      paint: {
        "icon-color": "rgba(116, 140, 225, 1)",
        "icon-halo-color": "rgba(230, 217, 211, 1)",
        "icon-opacity": 1,
        "text-opacity": 0.8,
        "text-color": "rgba(0, 0, 0, 1)",
        "text-halo-color": "hsl(0, 0%, 100%)",
      },
    },
    {
      id: "igensys.road_minor_Dir",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_minor",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all", ["in", "direction_", "B", "F", "T"]],
      layout: {
        "text-field": "",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.7,
        visibility: "visible",
        "symbol-placement": "line-center",
        "text-font": [],
        "text-keep-upright": false,
        "text-justify": "auto",
        "text-allow-overlap": false,
        "text-ignore-placement": false,
        "icon-image": "arrow",
        "icon-text-fit": "none",
        "text-pitch-alignment": "auto",
        "icon-optional": false,
        "text-optional": false,
        "text-size": 3,
      },
      paint: {
        "icon-color": "rgba(105, 134, 230, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(130, 117, 107, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(233, 224, 224, 1)",
        "icon-opacity": 1,
      },
    },
    {
      id: "igensys.road_minor_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_minor",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{street_nam}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 0.7,
        visibility: "visible",
        "symbol-placement": "line-center",
        "text-font": ["Arial Unicode MS Regular"],
        "text-keep-upright": false,
        "text-justify": "auto",
        "text-allow-overlap": false,
        "text-ignore-placement": false,
        "icon-text-fit": "none",
        "text-pitch-alignment": "auto",
        "icon-optional": false,
        "text-optional": false,
        "text-anchor": "center",
        "text-size": 3,
      },
      paint: {
        "icon-color": "rgba(105, 134, 230, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(87, 80, 68, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(233, 224, 224, 1)",
        "icon-opacity": 1,
      },
    },
    {
      id: "igensys.road_private_Dir",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_private",
      minzoom: 17,
      maxzoom: 24,
      filter: ["all", ["in", "direction_", "B", "F", "T"]],
      layout: {
        "text-field": "{street_nam}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "symbol-placement": "line-center",
        "text-size": 7,
        "text-line-height": 1.2,
        "text-font": ["Arial Unicode MS Regular"],
        "text-keep-upright": false,
        "text-justify": "auto",
        "text-allow-overlap": false,
        "text-ignore-placement": false,
        "icon-image": "arrow",
        "icon-size": 0.7,
        "icon-text-fit": "both",
        "icon-keep-upright": false,
        "text-optional": true,
        "icon-rotation-alignment": "auto",
        "icon-optional": true,
        "icon-anchor": "center",
        "icon-pitch-alignment": "auto",
      },
      paint: {
        "icon-color": "rgba(105, 134, 230, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(130, 117, 107, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(233, 224, 224, 1)",
        "text-translate-anchor": "viewport",
      },
    },
    {
      id: "igensys.road_private_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_private",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{street_nam}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "symbol-placement": "line-center",
        "text-size": 7,
        "text-line-height": 1.2,
        "text-font": ["Arial Unicode MS Regular"],
        "text-keep-upright": false,
        "text-justify": "auto",
        "text-allow-overlap": false,
        "text-ignore-placement": false,
        "icon-size": 0.7,
        "icon-text-fit": "none",
        "icon-keep-upright": false,
        "text-optional": true,
        "icon-rotation-alignment": "auto",
        "icon-optional": true,
        "icon-anchor": "center",
        "icon-pitch-alignment": "auto",
      },
      paint: {
        "icon-color": "rgba(105, 134, 230, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(87, 80, 68, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(233, 224, 224, 1)",
        "text-translate-anchor": "viewport",
      },
    },
    {
      id: "igensys.road_major_urban_Dir",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_major_urban",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all", ["in", "direction_", "B", "F", "T"]],
      layout: {
        "text-field": "{street_nam}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 1.2,
        visibility: "visible",
        "symbol-placement": "line-center",
        "text-size": 7,
        "text-line-height": 1.2,
        "text-font": ["Arial Unicode MS Regular"],
        "text-keep-upright": false,
        "text-justify": "auto",
        "text-allow-overlap": false,
        "text-ignore-placement": false,
        "icon-image": "arrow",
        "text-optional": true,
      },
      paint: {
        "icon-color": "rgba(188, 195, 227, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(130, 117, 107, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(233, 224, 224, 1)",
      },
    },
    {
      id: "igensys.road_major_urban_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_major_urban",
      minzoom: 12,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{street_nam}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 1.2,
        visibility: "visible",
        "symbol-placement": "line-center",
        "text-size": 7,
        "text-line-height": 1.2,
        "text-font": ["Arial Unicode MS Regular"],
        "text-keep-upright": false,
        "text-justify": "auto",
        "text-allow-overlap": false,
        "text-ignore-placement": false,
        "text-optional": true,
      },
      paint: {
        "icon-color": "rgba(188, 195, 227, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(87, 80, 68, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(233, 224, 224, 1)",
      },
    },
    {
      id: "igensys.road_major_district_Dir",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_major_district",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["in", "direction_", "B", "F", "T"]],
      layout: {
        "text-field": "{street_nam}",
        "text-size": 8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 1.2,
        visibility: "visible",
        "symbol-placement": "line-center",
        "text-font": ["Arial Unicode MS Regular"],
        "text-keep-upright": false,
        "icon-image": "arrow",
        "text-optional": true,
      },
      paint: {
        "icon-color": "rgba(188, 195, 227, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(130, 117, 107, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(233, 224, 224, 1)",
      },
    },
    {
      id: "igensys.road_major_district_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_major_district",
      minzoom: 12,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{street_nam}",
        "text-size": 8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        "icon-size": 1.2,
        visibility: "visible",
        "symbol-placement": "line-center",
        "text-font": ["Arial Unicode MS Regular"],
        "text-keep-upright": false,
        "text-optional": true,
      },
      paint: {
        "icon-color": "rgba(188, 195, 227, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(87, 80, 68, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(233, 224, 224, 1)",
      },
    },
    {
      id: "igensys.road_state_highway_Dir",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_state_highways",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all", ["in", "direction_", "B", "F", "T"]],
      layout: {
        "text-field": "",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "symbol-placement": "line",
        "text-font": [],
        "text-allow-overlap": false,
        "text-ignore-placement": false,
        "text-justify": "auto",
        "text-anchor": "center",
        "text-keep-upright": false,
        "icon-image": "arrow",
        "icon-text-fit": "none",
        "symbol-avoid-edges": true,
        "text-rotation-alignment": "auto",
        "text-max-angle": 0,
        "text-pitch-alignment": "auto",
        "symbol-spacing": 250,
        "symbol-z-order": "auto",
        "icon-size": 0.9,
        "text-optional": true,
      },
      paint: {
        "icon-color": "rgba(188, 195, 227, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(130, 117, 107, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(233, 224, 224, 1)",
      },
    },
    {
      id: "igensys.road_state_highway_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_state_highways",
      minzoom: 10,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{street_nam}",
        "text-size": 8,
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "symbol-placement": "line-center",
        "text-font": ["Arial Unicode MS Regular"],
        "text-allow-overlap": false,
        "text-ignore-placement": false,
        "text-justify": "auto",
        "text-anchor": "right",
        "text-keep-upright": true,
        "icon-text-fit": "height",
        "symbol-avoid-edges": true,
        "text-rotation-alignment": "auto",
        "text-max-angle": 0,
        "text-pitch-alignment": "auto",
        "icon-size": 0.9,
        "text-optional": true,
      },
      paint: {
        "icon-color": "rgba(188, 195, 227, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(87, 80, 68, 1)",
        "text-opacity": 1,
        "text-halo-color": "rgba(233, 224, 224, 1)",
      },
    },
    {
      id: "igensys.road_national_Dir",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_national_highways",
      minzoom: 13,
      maxzoom: 24,
      filter: ["all", ["in", "direction_", "B", "T", "F"]],
      layout: {
        "text-field": "",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "symbol-placement": "line-center",
        "text-font": [],
        "icon-image": "arrow",
        "icon-text-fit": "none",
        "icon-optional": false,
        "icon-rotation-alignment": "auto",
        "text-allow-overlap": false,
        "text-ignore-placement": false,
        "symbol-avoid-edges": true,
        "text-justify": "auto",
        "text-anchor": "center",
        "text-keep-upright": false,
        "text-optional": true,
        "icon-anchor": "center",
        "icon-keep-upright": false,
        "text-radial-offset": 0,
        "symbol-z-order": "auto",
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "text-max-angle": 0,
        "icon-size": 0.9,
      },
      paint: {
        "text-color": "rgba(130, 117, 107, 1)",
        "text-halo-color": "rgba(233, 224, 224, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
      },
    },
    {
      id: "igensys.road_national_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "road_national_highways",
      minzoom: 8,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{street_nam}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "symbol-placement": "line-center",
        "text-size": 9,
        "text-font": ["Arial Unicode MS Regular"],
        "icon-text-fit": "none",
        "icon-optional": false,
        "icon-rotation-alignment": "auto",
        "symbol-spacing": 250,
        "text-allow-overlap": false,
        "text-ignore-placement": false,
        "symbol-avoid-edges": true,
        "text-justify": "auto",
        "text-anchor": "center",
        "text-keep-upright": false,
        "text-optional": false,
        "icon-anchor": "center",
        "icon-keep-upright": false,
        "text-variable-anchor": ["center"],
        "text-radial-offset": 0,
        "symbol-z-order": "auto",
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
      },
      paint: {
        "text-color": "rgba(87, 80, 68, 1)",
        "text-halo-color": "rgba(233, 224, 224, 1)",
        "text-opacity": 1,
        "icon-opacity": 1,
      },
    },
    {
      id: "igensys.admin_4_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "admin_boundary_name_4",
      minzoom: 16,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{admin_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 11,
        "icon-pitch-alignment": "auto",
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "text-justify": "auto",
        "text-anchor": "top",
        "text-keep-upright": false,
        "text-transform": "uppercase",
        "text-font": ["Cabin Regular"],
      },
      paint: {
        "icon-color": "rgba(205, 212, 233, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(6, 5, 5, 1)",
        "text-translate-anchor": "map",
        "icon-translate-anchor": "map",
        "icon-opacity": 1,
        "text-opacity": 1,
        "text-halo-color": "rgba(241, 234, 234, 1)",
      },
    },
    {
      id: "igensys.admin_5_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "admin_boundary_name_5",
      minzoom: 14,
      maxzoom: 24,
      filter: ["all"],
      layout: {
        "text-field": "{admin_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-pitch-alignment": "auto",
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "text-transform": "uppercase",
        "text-font": ["Cabin Regular"],
        "text-size": 11,
        "text-variable-anchor": ["top"],
        "text-allow-overlap": false,
        "text-justify": "auto",
        "text-anchor": "top",
        "text-padding": 5,
      },
      paint: {
        "icon-color": "rgba(205, 212, 233, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(0, 0, 0, 1)",
        "text-translate-anchor": "map",
        "icon-translate-anchor": "map",
        "icon-opacity": 1,
        "text-opacity": 1,
        "text-halo-color": "rgba(241, 234, 234, 1)",
      },
    },
    {
      id: "igensys.admin_5_D-Pr1",
      type: "symbol",
      source: "igensys",
      "source-layer": "admin_boundary_name_5",
      minzoom: 10,
      maxzoom: 24,
      filter: [
        "any",
        ["==", "admin_name", "Church Gate Station"],
        ["==", "admin_name", "Haji Ali"],
        ["==", "admin_name", "Worli Sea Face"],
        ["==", "admin_name", "Sion"],
        ["==", "admin_name", "Chembur"],
        ["==", "admin_name", "Bandra West"],
        ["==", "admin_name", "Kurla West"],
        ["==", "admin_name", "Juhu"],
        ["==", "admin_name", "Iit Powai"],
        ["==", "admin_name", "Borivali West"],
        ["==", "admin_name", "Bharti Vidhyapeeth"],
        ["==", "admin_name", "Panvel City"],
        ["==", "admin_name", "MIDC"],
        ["==", "admin_name", "Dahisar (Mori)"],
        ["==", "admin_name", "Ambernath"],
        ["==", "admin_name", "Dombivli Industrial Estate"],
        ["==", "admin_name", "Naigaon West"],
        ["==", "admin_name", "Adarsh Nagar"],
        ["==", "admin_name", "Aksa Beach"],
        ["==", "admin_name", "Andheri Market"],
        ["==", "admin_name", "Antop Hill"],
        ["==", "admin_name", "Arthur Road"],
        ["==", "admin_name", "Bandra Kurla Complex"],
        ["==", "admin_name", "Century Mill"],
        ["==", "admin_name", "Dadar Station"],
        ["==", "admin_name", "Fort"],
        ["==", "admin_name", "Ghatkopar Station"],
        ["==", "admin_name", "Hiranandani Estate"],
        ["==", "admin_name", "Kalbadevi"],
        ["==", "admin_name", "Kurla Station"],
        ["==", "admin_name", "Lalbaug"],
        ["==", "admin_name", "Model Town"],
        ["==", "admin_namee", "Nagpada"],
        ["==", "admin_name", "New Airport Colony (Aai)"],
        ["==", "admin_name", "Panvel City"],
        ["==", "admin_name", "Seawoods"],
        ["==", "admin_name", "Ashok Nagar"],
        ["==", "admin_name", "Malabar Hill"],
        ["==", "admin_name", "Nalasopara East"],
        ["==", "admin_name", "Vasai Midc"],
        ["==", "admin_name", "Virar West"],
        ["==", "admin_name", "Goregaon Sports Complex"],
      ],
      layout: {
        "text-field": "{admin_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-pitch-alignment": "auto",
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "text-transform": "uppercase",
        "text-font": ["Cabin Regular"],
        "text-size": 12,
        "text-allow-overlap": false,
        "text-justify": "auto",
        "text-anchor": "top",
      },
      paint: {
        "text-color": "rgba(37, 34, 34, 1)",
        "text-translate-anchor": "map",
        "icon-translate-anchor": "map",
        "icon-opacity": 1,
        "text-opacity": 1,
        "text-halo-color": "rgba(241, 234, 234, 1)",
        "text-halo-width": 2,
        "text-halo-blur": 1,
      },
    },
    {
      id: "igensys.admin_3_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "admin_boundary_name_3",
      minzoom: 9,
      maxzoom: 12,
      filter: [
        "all",
        ["!=", "admin_name", "Thane"],
        ["!=", "admin_name", "Palghar"],
      ],
      layout: {
        "text-field": "{admin_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "icon-size": 0.5,
        "icon-pitch-alignment": "auto",
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "icon-rotation-alignment": "auto",
        "text-justify": "auto",
        "text-anchor": "top",
        "text-font": ["Cabin Regular"],
        "text-transform": "uppercase",
        "text-size": 12,
      },
      paint: {
        "icon-color": "rgba(205, 212, 233, 1)",
        "icon-halo-color": "rgba(225, 212, 208, 1)",
        "text-color": "rgba(6, 5, 5, 1)",
        "text-translate-anchor": "map",
        "icon-translate-anchor": "map",
        "icon-opacity": 1,
        "text-opacity": 1,
        "text-halo-color": "rgba(241, 234, 234, 1)",
      },
    },
    {
      id: "igensys.admin_2_D",
      type: "symbol",
      source: "igensys",
      "source-layer": "admin_boundary_name_2",
      minzoom: 8,
      maxzoom: 10,
      filter: ["all"],
      layout: {
        "text-field": "{admin_name}",
        "icon-allow-overlap": false,
        "icon-ignore-placement": false,
        visibility: "visible",
        "text-size": 12,
        "text-allow-overlap": false,
        "text-ignore-placement": false,
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "symbol-z-order": "auto",
        "text-justify": "auto",
        "icon-optional": false,
        "text-anchor": "top",
        "text-font": ["Cabin Regular"],
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": "rgba(6, 5, 5, 1)",
        "text-translate-anchor": "map",
        "icon-translate-anchor": "map",
        "text-halo-color": "rgba(241, 234, 234, 1)",
        "text-halo-width": 2,
        "text-opacity": 1,
      },
    },
  ],
  id: "osm-liberty",
};
